### ISSUE TITLE
fix styling for home page events

### ISSUE THREAD

**Issue by adityanandanx** [adityanandanx/tdh-ems#5]
# Issue
![image](https://github.com/adityanandanx/tdh-ems/assets/61308761/dc8555a9-3ec8-4afc-8998-1325e1b6c0db)
- The event cards on the home page are not of equal width 

# To Reproduce
- change description of an event to have long content

# Requirements
- Use grid layout with 3 columns instead of flex to make sure all the cards are of equal width.
- Make sure to make it responsive by reducing the number of columns to 1 for smaller screens.

**Comment by manvichaudhary55** [comment]
Please assign this issue to me .

**Comment by adityanandanx** [comment]
@manvichaudhary55 done

**Comment by manvichaudhary55** [comment]
I have send the pull request , please review it .
