### ISSUE TITLE
remove unnecessary console logs and fix key prop warnings

### ISSUE THREAD

**Issue by adityanandanx** [adityanandanx/tdh-ems#6]
# Issue
![image](https://github.com/adityanandanx/tdh-ems/assets/61308761/2ddeca41-72fd-456f-a658-cec6c155ffec)
- I left random console logs which was used for debugging everywhere in the code 😓 
- Also there's key prop warning somewhere

# Requirements
- No console logs should be visible on any page
- Also fix any key prop warning

# Hints
- search for `console.log` keyword using `Ctrl + shift + f` shortcut key and remove all those statements.
- just search for `map(` keyword using `Ctrl + shift + f` shortcut key on vscode to find every occurrence of the map function and add in a key prop to the component/element being returned

**Comment by Sandeep18JS** [comment]
Assign this issue to me .

**Comment by adityanandanx** [comment]
@Sandeep18JS done

**Comment by vivekrawat21** [comment]
@Sandeep18JS assign me this issue

**Comment by adityanandanx** [comment]
@vivekrawat21 assigned the issue to you

**Comment by vivekrawat21** [comment]
@adityanandanx  thanks for assigning the issue i have created a pull request regarding this issue

**Comment by vivekrawat21** [comment]
thanks for merging looking forward to contribute more :)
